# Generated by Django 2.2.4 on 2019-09-25 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_tripblog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatbot_category', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatbotQA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatbot_question', models.CharField(max_length=255)),
                ('chatbot_answer', models.CharField(max_length=255)),
                ('chatbot_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tripblog.ChatbotCategory')),
            ],
        ),
    ]
