# Generated by Django 2.2.4 on 2019-10-07 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_tripblog', '0002_chatbotcategory_chatbotqa'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotCategory_ch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatbot_category_ch', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatbotQA_ch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatbot_question', models.CharField(max_length=255)),
                ('chatbot_answer', models.CharField(max_length=255)),
                ('chatbot_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tripblog.ChatbotCategory_ch')),
            ],
        ),
    ]
