# Generated by Django 2.2.4 on 2019-10-08 09:01

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tripblog', '0003_chatbotcategory_ch_chatbotqa_ch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('data', django_mysql.models.JSONField(default=dict)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='user_account',
            field=models.CharField(default=0, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
