# Generated by Django 2.2.4 on 2019-10-08 09:06

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tripblog', '0004_auto_20191008_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBlogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_picture', models.CharField(max_length=20)),
                ('blog_title', models.CharField(max_length=40)),
                ('blog_content', django_mysql.models.JSONField(default=dict)),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tripblog.User')),
            ],
        ),
    ]
