# Generated by Django 2.2.4 on 2019-10-08 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_tripblog', '0005_userblogs'),
        ('app_tripblog', '0004_auto_20191008_1920'),
    ]

    operations = [
    ]
