# Generated by Django 2.2.4 on 2019-10-09 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_tripblog', '0006_merge_20191008_2009'),
        ('app_tripblog', '0006_merge_20191008_2003'),
    ]

    operations = [
    ]
