# Generated by Django 2.2.4 on 2019-10-09 08:33

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tripblog', '0007_merge_20191009_1025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userblogs',
            old_name='blog_title',
            new_name='article_title',
        ),
        migrations.RemoveField(
            model_name='userblogs',
            name='blog_content',
        ),
        migrations.AddField(
            model_name='userblogs',
            name='article_content',
            field=django_mysql.models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='userblogs',
            name='cover_picture',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
