# Generated by Django 2.2.4 on 2019-10-16 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_tripblog', '0009_auto_20191009_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAlbums',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_picture', models.CharField(blank=True, max_length=20)),
                ('album_title', models.CharField(max_length=40)),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tripblog.User')),
            ],
        ),
        migrations.DeleteModel(
            name='Dog',
        ),
    ]
